language: node_js

node_js:
  - "0.10"

install:
  - npm -d install
  - npm install -g bower
  - bower install
  - npm install -g grunt-cli
  - npm install -g grunt

script:
  - grunt ci-test-only

after_script:
  - cat ./build/coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js